version: "3.3"

services:

  telegram-bot:
    build:
      context: .
    container_name: psychomatrix-bot
    command: sh -c "cd /usr/src/telegram-bot && python -m app"
    restart: always
    volumes:
      - .:/usr/src/telegram-bot
    networks:
      - psychomatrix-network
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  redis:
    image: redis:alpine
    container_name: psychomatrix-redis
    restart: always
    volumes:
      - ./redis/data/:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

networks:
  psychomatrix-network:
