version: "3"

services:

  telegram-bot:
    build:
      context: .
    container_name: psychomatrix-bot
    command: sh -c "cd /usr/src/telegram-bot && python -m app"
    restart: always
    depends_on:
      - redis
    volumes:
      - .:/usr/src/telegram-bot
    networks:
      - network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"

  redis:
    image: redis:alpine
    container_name: psychomatrix-redis
    restart: always
    volumes:
      - ./redis/data/:/data
    networks:
      - network
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"

networks:
  network:
